#!/usr/bin/env node
// Generated by LiveScript 1.3.1
var t1, fs, server, watch, index, cfgfile, main, config;
t1 = Date.now();
fs = require('fs');
server = require('./lib/server');
watch = require('./lib/watch');
index = require('./api/index');
if (/\.json$/.exec(process.argv[2] || '')) {
  cfgfile = process.argv[2];
}
if (!cfgfile) {
  cfgfile = 'config.json';
}
main = {
  opt: {
    api: index,
    startTime: t1
  },
  setOpt: function(o){
    return import$(this.opt, o);
  },
  init: function(){
    server.init(this.opt);
    return watch.init(this.opt);
  }
};
if (require.main === module) {
  if (fs.existsSync(cfgfile)) {
    config = JSON.parse(fs.readFileSync(cfgfile).toString());
    main.setOpt(config);
  }
  main.init();
}
module.exports = main;
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}
