// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('map', []);
x$.factory('mapOption', function(){
  var mapOption;
  return mapOption = {
    center: new google.maps.LatLng(22.624146, 120.320623),
    zoom: 13,
    minZoom: 8,
    maxZoom: 18,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    panControlOptions: {
      position: google.maps.ControlPosition.LEFT_CENTER
    },
    zoomControlOptions: {
      position: google.maps.ControlPosition.LEFT_CENTER
    },
    mapTypeControlOptions: {
      position: google.maps.ControlPosition.LEFT_CENTER
    }
  };
});
x$.factory('mapStyle', function(){
  var mapStyle;
  return mapStyle = [
    {
      "featureType": "road",
      "stylers": [{
        "saturation": -100
      }]
    }, {
      "featureType": "poi",
      "stylers": [{
        "saturation": -100
      }]
    }, {
      "featureType": "transit",
      "stylers": [{
        "saturation": -100
      }]
    }
  ];
});
x$.service('map', function(mapStyle, mapOption){
  return import$(this, {
    create: function(id){
      var x$, map;
      x$ = map = new google.maps.Map(document.getElementById(id), mapOption);
      x$.set('styles', mapStyle);
      return x$;
    }
  });
});
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}