// Generated by LiveScript 1.3.1
var app, browserWindow, crashReporter, fs, mainWindow;
app = require('app');
browserWindow = require('browser-window');
crashReporter = require('crash-reporter');
fs = require('fs');
crashReporter.start();
mainWindow = null;
app.on('window-all-closed', function(){
  if (process.paltform !== 'darwin') {
    return app.quit();
  }
});
app.on('ready', function(){
  var mainWindow;
  mainWindow = new browserWindow({
    width: 800,
    height: 600
  });
  mainWindow.loadUrl("file://" + __dirname + "/index.html");
  mainWindow.openDevTools();
  console.log(fs.readFileSync('main.ls').toString());
  console.log(fs.readFileSync('/Users/tkirby/workspace/zbryikt/electron-test/main.ls').toString());
  return mainWindow.on('closed', function(){
    var mainWindow;
    return mainWindow = null;
  });
});